<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <InternalsVisibleTo Include="Forge.NotificationsTests" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Forge.Auditing/Forge.Auditing.csproj" />
    <ProjectReference Include="../Forge.Core/Forge.Core.csproj" />
    <ProjectReference Include="../Forge.Templates/Forge.Templates.csproj" />
  </ItemGroup>
</Project>
