<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Forge.Auditing/Forge.Auditing.csproj" />
    <ProjectReference Include="../Forge.Core/Forge.Core.csproj" />
    <ProjectReference Include="../Forge.Events/Forge.Events.csproj" />
    <ProjectReference Include="../Forge.Tenancy/Forge.Tenancy.csproj" />
  </ItemGroup>
</Project>
