<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ForgeStack.Modularity" Version="$(ForgeVersion)" />
    <PackageReference Include="ForgeStack.Persistence.SqlServer" Version="$(ForgeVersion)" />
  </ItemGroup>
</Project>
