<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../../src/Forge.Auditing/Forge.Auditing.csproj" />
    <ProjectReference Include="../../../src/Forge.Events/Forge.Events.csproj" />
    <ProjectReference Include="../../../src/Forge.Tenancy/Forge.Tenancy.csproj" />
    <ProjectReference Include="../../../src/Forge.Web/Forge.Web.csproj" />
    <ProjectReference Include="../../../src/Forge.Modularity/Forge.Modularity.csproj" />
    <ProjectReference Include="../../../src/Forge.Notifications/Forge.Notifications.csproj" />
    <ProjectReference Include="../../../src/Forge.Persistence.SqlServer/Forge.Persistence.SqlServer.csproj" />
  </ItemGroup>
</Project>
