<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Forge.Core/Forge.Core.csproj" />
    <ProjectReference Include="../Forge.Tenancy/Forge.Tenancy.csproj" />
  </ItemGroup>
</Project>
